services:
  - type: web
    name: helicorp-test
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_API_PROXY_TARGET
        value: https://java-x07o.onrender.com
